networks:
  cat-pinterest-net:
    driver: bridge

services:
  cat-pinterest-api:
    container_name: cat-pinterest-api
    build:
      context: ./api/
    environment:
      NODE_ENV: prod
    depends_on:
      cat-pinterest-api-pg:
        condition: service_healthy
    networks:
      - cat-pinterest-net
    ports:
      - "3000:3000"

  cat-pinterest-api-pg:
    container_name: cat-pinterest-api-pg
    image: postgres:14
    networks:
      - cat-pinterest-net
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: support_lk_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10

  proxy:
    container_name: cat-pinterest-proxy
    image: nginx:1.24-alpine-slim
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
    ports:
      - "8080:80"
    depends_on:
      cat-pinterest-api:
        condition: service_started
    networks:
      - cat-pinterest-net

  cat-pinterest-front:
    container_name: cat-pinterest-front
    build:
      context: ./front/
    networks:
      - cat-pinterest-net
    environment:
      NODE_ENV: prod
    ports:
      - "5731:5731"
